name: Build master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: make debs
      #- run: sudo apt install python3-sphinx-rtd-theme python3-sphinx-autobuild --yes
      - run: >
          python3 -m venv .
          make debs
      - run: >
          python3 -m venv .
          make

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} 
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-personal-access-token-personal_token
          publish_dir: _build
          external_repository: Kakadu/kakadu.github.io
          publish_branch: master
          destination_dir: riscv-course-2023
          enable_jekyll: true
